name: zsar_project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy<2.0
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - opencv
  - tqdm
  - transformers
  - pip
