import collections
import pprint

import pandas as pd

from src.utils.constants import TEST_CSV

#  only used for visualisation of ucf101 results in confusion matrix to group the classes
ucf101_categories_camelcase = {
    "Body-Motion Only": [
        "BabyCrawling",
        "BlowingCandles",
        "BodyWeightSquats",
        "HandstandPushups",
        "HandstandWalking",
        "JumpingJack",
        "Lunges",
        "PullUps",
        "PushUps",
        "RockClimbingIndoor",
        "RopeClimbing",
        "Swing",
        "TaiChi",
        "TrampolineJumping",
        "WalkingWithDog",
        "WallPushups",
    ],
    "Human-Human Interaction": [
        "BandMarching",
        "Haircut",
        "HeadMassage",
        "MilitaryParade",
        "SalsaSpin",
    ],
    "Human-Object Interaction": [
        "ApplyEyeMakeup",
        "ApplyLipstick",
        "BlowDryHair",
        "BrushingTeeth",
        "CuttingInKitchen",
        "Hammering",
        "HulaHoop",
        "JugglingBalls",
        "JumpRope",
        "Knitting",
        "Mixing",
        "MoppingFloor",
        "Nunchucks",
        "PizzaTossing",
        "ShavingBeard",
        "SkateBoarding",
        "SoccerJuggling",
        "Typing",
        "WritingOnBoard",
        "YoYo",
    ],
    "Playing Musical Instruments": [
        "Drumming",
        "PlayingCello",
        "PlayingDaf",
        "PlayingDhol",
        "PlayingFlute",
        "PlayingGuitar",
        "PlayingPiano",
        "PlayingSitar",
        "PlayingTabla",
        "PlayingViolin",
    ],
    "Sports": [
        "Archery",
        "BalanceBeam",
        "BaseballPitch",
        "Basketball",
        "BasketballDunk",
        "BenchPress",
        "Biking",
        "Billiards",
        "Bowling",
        "BoxingPunchingBag",
        "BoxingSpeedBag",
        "BreastStroke",
        "CleanAndJerk",
        "CliffDiving",
        "CricketBowling",
        "CricketShot",
        "Diving",
        "Fencing",
        "FieldHockeyPenalty",
        "FloorGymnastics",
        "FrisbeeCatch",
        "FrontCrawl",
        "GolfSwing",
        "HammerThrow",
        "HighJump",
        "HorseRace",
        "HorseRiding",
        "IceDancing",
        "JavelinThrow",
        "Kayaking",
        "LongJump",
        "ParallelBars",
        "PoleVault",
        "PommelHorse",
        "Punch",
        "Rafting",
        "Rowing",
        "Shotput",
        "Skiing",
        "Skijet",
        "SkyDiving",
        "SoccerPenalty",
        "StillRings",
        "SumoWrestling",
        "Surfing",
        "TableTennisShot",
        "TennisSwing",
        "ThrowDiscus",
        "UnevenBars",
        "VolleyballSpiking",
    ],
}
