# -*- coding: utf-8 -*-
"""CLIP_UCF101_runner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzWm_3UOYdw236R9C-28jEMhCFJ32ZTR

# UCF101 Dataset embeddings generator script

This notebook is for using the CLIP model to generate the embeddings/features for each frame of the videos in the UCF101 dataset. Google Colab is used as it provides easy access to a powerful (T4) GPU. This massively reduces the time to perform inference on all the frames for the videos that are being processed in this notebook.
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers tqdm

"""## Define the paths for how to process the data

You must specify the paths to find the .zip file containing the dataset folder, where to save the output, and more...
"""

import os
from pathlib import Path

# Avoid Hugging Face "create an API key" prompts
os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "1"

# Path to the zip with the dataset folder inside
DRIVE_ZIP_PATH = "/content/drive/My Drive/Dissertation/data/ucf101_subset.zip"

# Path to the current session's (local) data directory
LOCAL_DATA_DIR = Path("/content") / "data"

# Name of the directory of [videos + csv]
DATASET_DIR_NAME = "ucf101_subset"

# Path to directory of the dataset
LOCAL_DATASET_ROOT = LOCAL_DATA_DIR / DATASET_DIR_NAME

# Name of the CSV file containing information on the videos [csv]
DATASET_CSV_FILE_NAME = "test.csv"

# Path to the dataset's CSV file containing information about videos
LOCAL_CSV_PATH = LOCAL_DATASET_ROOT / DATASET_CSV_FILE_NAME

# Location where the embeddings will be saved
GDRIVE_OUTPUT_DIR = Path("/content/drive/My Drive/Dissertation/data/ucf101_embeddings/")

"""## Unzip the dataset folder"""

print("Unzipping video data... (this may take a few minutes)")
!unzip -oq "{DRIVE_ZIP_PATH}" -d "{LOCAL_DATA_DIR}"
print("Data unzipped successfully.")

# Check that the data has been unzipped correctly
!ls "{str(LOCAL_DATA_DIR)}"
print()
!ls "{str(LOCAL_DATA_DIR / 'ucf101_subset')}" | head -n 5
print()
!ls "{str(LOCAL_DATA_DIR / 'ucf101_subset' / 'test')}" | head -n 5
print()
!ls "{str(LOCAL_DATA_DIR / 'ucf101_subset' / 'test' / 'Swing')}" | head -n 5

"""## Load the model in for inference"""

import torch
from transformers import CLIPProcessor, CLIPModel
import pandas as pd
import cv2
from tqdm import tqdm
import time
import numpy as np

# Set up model
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_ID = "openai/clip-vit-base-patch32"
BATCH_SIZE = 64

print(f"Loading CLIP model '{MODEL_ID}' onto {DEVICE}...")
model = CLIPModel.from_pretrained(MODEL_ID).to(DEVICE)
processor = CLIPProcessor.from_pretrained(MODEL_ID)
print("Model loaded.")

"""## Load in the dataset information file (CSV)"""

df = pd.read_csv(LOCAL_CSV_PATH)
df.head()

def extract_all_frames(video_path: Path):
    frames = []
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print(f"Warning: Cannot open {video_path}")
        return []

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()
    return frames

"""## Test run of running inference on one video"""

# Estimate Time to process videos
print("Starting Time Estimation (1 Video)")
start_time = time.time()

# Get one video to test
test_row = df.iloc[0]
test_video_path = LOCAL_DATASET_ROOT / test_row['clip_path'].lstrip('/')

test_frames = extract_all_frames(test_video_path)

with torch.no_grad():
    for i in range(0, len(test_frames), BATCH_SIZE):
        batch = test_frames[i : i + BATCH_SIZE]
        # The processor handles resizing (to 224x224) and normalization
        inputs = processor(text=None, images=batch, return_tensors="pt", padding=True)
        inputs = {k: v.to(DEVICE) for k, v in inputs.items()}
        model.get_image_features(**inputs) # Run inference

end_time = time.time()

time_per_video = end_time - start_time
total_videos = len(df)
estimated_total_time_min = (time_per_video * total_videos) / 60

print(f"Time for 1 video ({len(test_frames)} frames): {time_per_video:.2f} seconds.")
print(f"Estimated time to process {total_videos} videos: {estimated_total_time_min:.2f} minutes.")
print("Time Estimation Complete")

"""## Run inference on all videos and save embeddings to output directory

This may take a long time (as expected).

To make this run as fast as possible, make sure to switch the google colab runtime to one with a GPU.

'tqdm' provides a live progress bar below.
"""

print(f"Starting Full Embedding Pre-computation ({total_videos} videos)")

for index, row in tqdm(df.iterrows(), total=df.shape[0], desc="Processing videos"):
    video_relative_path = Path(row['clip_path'].lstrip('/'))
    # Full Path to the video
    full_video_path = LOCAL_DATASET_ROOT / video_relative_path

    embedding_relative_path = video_relative_path.with_suffix('.pt')
    # Path to output location for this video
    output_path = GDRIVE_OUTPUT_DIR / embedding_relative_path

    # Convert clip_path in DataFrame to the new embedding relative path format
    df.at[index, "clip_path"] = str(embedding_relative_path)

    # This makes the script resumable if it crashes
    if output_path.exists():
        continue

    # Create directories if they don't exist
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Get the video's frames
    frames = extract_all_frames(full_video_path)

    all_embeddings = []
    with torch.no_grad():
        for i in range(0, len(frames), BATCH_SIZE):
            # The processor handles resizing (to 224x224) and normalization
            batch = frames[i:i+BATCH_SIZE]
            inputs = processor(text=None, images=batch, return_tensors="pt", padding=True)
            inputs = {k: v.to(DEVICE) for k,v in inputs.items()}
            all_embeddings.append(model.get_image_features(**inputs).cpu())

    if not all_embeddings:
        print(f"Warning: No embeddings generated for {full_video_path}, skipping.")
        continue

    # Combine all embeddings into one tensor
    final_embeddings = torch.cat(all_embeddings, dim=0)
    torch.save(final_embeddings, output_path)

updated_csv_path = GDRIVE_OUTPUT_DIR / DATASET_CSV_FILE_NAME
df.to_csv(updated_csv_path, index=False)

print("\nPre-computation Finished!")

"""## The new video embeddings dataset can be found in your output directory."""

